const lazy_links = [
	{
		loadChildren:
			"../pages/_pay/pay-receive/pay-receive.module#PayReceivePageModule",
		name: "pay-receive",
		segment: "pay-receive",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["pay-receive"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-about-ibt/account-about-ibt.module#AccountAboutIbtPageModule",
		name: "account-about-ibt",
		segment: "account-about-ibt",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-about-ibt"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-dapp-list/account-dapp-list.module#AccountDappListPageModule",
		name: "account-dapp-list",
		segment: "account-dapp-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-dapp-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-info/account-info.module#AccountInfoPageModule",
		name: "account-info",
		segment: "account-info",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-info"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-miner-list/account-miner-list.module#AccountMinerListPageModule",
		name: "account-miner-list",
		segment: "account-miner-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-miner-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-my-contacts/account-my-contacts.module#AccountMyContactsPageModule",
		name: "account-my-contacts",
		segment: "account-my-contacts",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-my-contacts"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-my-transaction-list/account-my-transaction-list.module#AccountMyTransactionListPageModule",
		name: "account-my-transaction-list",
		segment: "account-my-transaction-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-my-transaction-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-peer-list/account-peer-list.module#AccountPeerListPageModule",
		name: "account-peer-list",
		segment: "account-peer-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-peer-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-scan-add-contact/account-scan-add-contact.module#AccountScanAddContactPageModule",
		name: "account-scan-add-contact",
		segment: "account-scan-add-contact",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-scan-add-contact"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-set-username/account-set-username.module#AccountSetUsernamePageModule",
		name: "account-set-username",
		segment: "account-set-username",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-set-username"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-settings/account-settings.module#AccountSettingsPageModule",
		name: "account-settings",
		segment: "account-settings",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-settings"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_chain/chain-block-detail/chain-block-detail.module#ChainBlockDetailPageModule",
		name: "chain-block-detail",
		segment: "chain-block-detail",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["chain-block-detail"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_chain/chain-transaction-detail/chain-transaction-detail.module#ChainTransactionDetailPageModule",
		name: "chain-transaction-detail",
		segment: "chain-transaction-detail",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["chain-transaction-detail"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_dapp/dapp-bill/dapp-bill.module#DappBillPageModule",
		name: "dapp-bill",
		segment: "dapp-bill",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["dapp-bill"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_dapp/dapp-detail/dapp-detail.module#DappDetailPageModule",
		name: "dapp-detail",
		segment: "dapp-detail",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["dapp-detail"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_dapp/dapp-publish-detail/dapp-publish-detail.module#DappPublishDetailPageModule",
		name: "DappPublishDetailPage",
		segment: "dapp-publish-detail",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["dapp-publish-detail"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_dapp/dapp-publish-list/dapp-publish-list.module#DappPublishListPageModule",
		name: "DappPublishListPage",
		segment: "dapp-publish-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["dapp-publish-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_account/account-add-contact/account-add-contact.module#AccountAddContactPageModule",
		name: "account-add-contact",
		segment: "account-add-contact",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["account-add-contact"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_settings/settings-cache-manage/settings-cache-manage.module#SettingsCacheManagePageModule",
		name: "settings-cache-manage",
		segment: "settings-cache-manage",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["settings-cache-manage"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_settings/settings-lang/settings-lang.module#SettingsLangPageModule",
		name: "settings-lang",
		segment: "settings-lang",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["settings-lang"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_settings/settings-set-default-fee/settings-set-default-fee.module#SettingsSetDefaultFeePageModule",
		name: "settings-set-default-fee",
		segment: "settings-set-default-fee",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["settings-set-default-fee"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_settings/settings-set-pay-pwd/settings-set-pay-pwd.module#SettingsSetPayPwdPageModule",
		name: "settings-set-pay-pwd",
		segment: "settings-set-pay-pwd",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["settings-set-pay-pwd"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_vote/vote-delegate-detail/vote-delegate-detail.module#VoteDelegateDetailPageModule",
		name: "vote-delegate-detail",
		segment: "vote-delegate-detail",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["vote-delegate-detail"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_vote/vote-income-logs/vote-income-logs.module#VoteIncomeLogsPageModule",
		name: "vote-income-logs",
		segment: "vote-income-logs",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["vote-income-logs"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/_vote/vote-list/vote-list.module#VoteListPageModule",
		name: "vote-list",
		segment: "vote-list",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["vote-list"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/cover-tabs-ctrl-model/cover-tabs-ctrl-model.module#CoverTabsCtrlModelPageModule",
		name: "cover-tabs-ctrl-model",
		segment: "cover-tabs-ctrl-model",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["cover-tabs-ctrl-model"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/iframepage/iframepage.module#IframepagePageModule",
		name: "iframepage",
		segment: "iframepage",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["iframepage"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/link-node/link-node.module#LinkNodePageModule",
		name: "link-node",
		segment: "link-node",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["link-node"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/pwd-input/pwd-input.module#PwdInputPageModule",
		name: "pwd-input",
		segment: "pwd-input",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["pwd-input"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/scan-nodes/scan-nodes.module#ScanNodesPageModule",
		name: "scan-nodes",
		segment: "scan-nodes",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["scan-nodes"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/search/search.module#SearchPageModule",
		name: "search",
		segment: "search",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["search"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren:
			"../pages/tab-account/tab-account.module#TabAccountPageModule",
		name: "tab-account",
		segment: "tab-account",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["tab-account"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/tab-chain/tab-chain.module#TabChainPageModule",
		name: "tab-chain",
		segment: "tab-chain",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["tab-chain"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/tab-pay/tab-pay.module#TabPayPageModule",
		name: "tab-pay",
		segment: "tab-pay",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["tab-pay"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/tab-vote/tab-vote.module#TabVotePageModule",
		name: "tab-vote",
		segment: "tab-vote",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["tab-vote"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
	{
		loadChildren: "../pages/tutorial/tutorial.module#TutorialPageModule",
		name: "tutorial",
		segment: "tutorial",
		priority: "low",
		defaultHistory: [],
		dataKeys: {},
		segmentParts: ["tutorial"],
		segmentPartsLen: 1,
		dataLen: 0,
		staticLen: 1,
	},
];

export default lazy_links;
